CREATE TABLE Employee
(
  EId NUMERIC(3) NOT NULL,
  EName VARCHAR(15),
  EEmail VARCHAR(15) NOT NULL,
  EPhone VARCHAR(15),
  PRIMARY KEY (EId)
);

CREATE TABLE Customer
(
  CId NUMERIC(3) NOT NULL,
  CName VARCHAR(15),
  CEmail VARCHAR(15) NOT NULL,
  CPhone VARCHAR(15),
  PRIMARY KEY (CId)
);

CREATE TABLE Dress
(
  DId NUMERIC(3) NOT NULL,
  Length NUMERIC(3),
  Color VARCHAR(15),
  Price NUMERIC(3) NOT NULL,
  PRIMARY KEY (DId)
);

CREATE TABLE Orders
(
  OId NUMERIC(3) NOT NULL,
  OrderDate DATE NOT NULL,
  ReturnDate DATE NOT NULL,
  EId NUMERIC(3) NOT NULL,
  DId NUMERIC(3) NOT NULL,
  CId NUMERIC(3) NOT NULL,
  SALARY NUMBER(3),
  PRIMARY KEY (OId),
  FOREIGN KEY (EId) REFERENCES Employee(EId),
  FOREIGN KEY (DId) REFERENCES Dress(DId),
  FOREIGN KEY (CId) REFERENCES Customer(CId)
);

CREATE TABLE Payment
(
  PId NUMERIC(3) NOT NULL,
  Price NUMERIC(3) NOT NULL,
  IsPaid NUMERIC(3) NOT NULL check(IsPaid = 0 or IsPaid = 1),
  FinePrice NUMERIC(3) NOT NULL,
  OId NUMERIC(3) NOT NULL,
  PRIMARY KEY (PId),
  FOREIGN KEY (OId) REFERENCES Orders(OId)
);

CREATE TABLE Laundry
(
  LId NUMERIC(3) NOT NULL,
  Cost NUMERIC(3) NOT NULL,
  LName VARCHAR(15),
  PickingDate DATE NOT NULL,
  OId NUMERIC(3) NOT NULL,
  PRIMARY KEY (LId),
  FOREIGN KEY (OId) REFERENCES Orders(OId)
);
